name: solana_js
description: Interface for interacting with Solana JS libraries
version: 1.0.0
homepage: https://chikin.run

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  solana:
    git:
      url: https://github.com/ChikinDeveloper/ext_solana_dart
      path: packages/solana
      ref: ae03e3929f39bd849198421647166b9adc1950fc

  json_annotation: ^4.0.1

dev_dependencies:
  lints: ^1.0.0
  json_serializable: ^5.0.0
